'''
Solved
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''


f = [1, 2]
x = 0
evenf = [2]

ret = 0

while f[-1] <= 4000000:
	#find next fib number
	x = sum(f)
	#move the numbers to next position to be added
	f[0] = f[1]
	f[1] = x

	#if even number add to the evenf out variable
	if f[-1] % 2 == 0:
		evenf.append(f[-1])

ret = sum(evenf)

print(f"The sum of all even valued terms in the Fibonacci sequence up to four million is {ret}")
